### ISSUE TITLE
Password is not being set 

### ISSUE THREAD

**Issue by awm086** [sous-chefs/mysql#539]
### Cookbook version
version '8.5.1'

### Chef-client version
12.18.31

### Platform Details
Mac OSX

### Scenario:
Use the mysql_service:
```
mysql_service 'default' do
  port '3306'
  run_user 'root'
  version node["mysql"]["version"]
  initial_root_password node["mysql"]["server_root_password"]
  socket "/var/run/mysqld/mysqld.sock"
  action [:create, :start]
end
```
### Steps to Reproduce:
Use mysql service to create an instance with password. 

### Expected Result:
A root password is properly generated for the instance
### Actual Result:
Password is empty. 

### More description:
When I run this to create an instance, I login to the vagrant box and I attempt to connect to myql with user root and password I am unable to connect. But if I omit the password it works connects. 

I can probably help if anyone can point me on as to how I can verify this sql query being run:

```
<<-EOS
<<-EOS
        set -e
        rm -rf /tmp/#{mysql_name}
        mkdir /tmp/#{mysql_name}

        cat > /tmp/#{mysql_name}/my.sql <<-'EOSQL'
UPDATE mysql.user SET #{password_column_name}=PASSWORD('#{root_password}')#{password_expired} WHERE user = 'root';
DELETE FROM mysql.user WHERE USER LIKE '';
FLUSH PRIVILEGES;
DELETE FROM mysql.db WHERE db LIKE 'test%';
DROP DATABASE IF EXISTS test ;
EOSQL

       #{db_init}
       #{record_init}

       while [ ! -f #{pid_file} ] ; do sleep 1 ; done
       kill `cat #{pid_file}`
       while [ -f #{pid_file} ] ; do sleep 1 ; done
       EOS
```

**Comment by whatcould** [comment]
In my experience, with 5.7 (and Ubuntu 18), the root password was not being set; it's possible to log on as the root user because "If you install 5.7 and don’t provide a password to the root user, it will use the auth_socket plugin" (as pointed out https://dzone.com/articles/change-user-password-in-mysql-57-with-plugin-auth).

Seems like a pretty big bug! 

I looked into why it wasn't being caught on the tests and it seems like the tests are pretty basic, and/or some weird Rspec fake-english is happening with "install_mysql_server_installation_package" and maybe it's actually testing the installation?
