### ISSUE TITLE
Version 9.0.0 apparmor error

### ISSUE THREAD

**Issue by itinneed** [sous-chefs/mysql#654]
### Cookbook version
9.0.0

### Chef-client version
16.6.14

### Platform Details
Ubuntu 18.04 virtualbox vm running on top of Windows 10

### Scenario:
Install MySQL 5.7

### Steps to Reproduce:
Run chef-client

### Expected Result:
Successful install

### Actual Result:
![1](https://user-images.githubusercontent.com/71790418/101700391-8fd0a400-3a42-11eb-8ac4-0e80b1a780ff.PNG)

[stacktrace.txt](https://github.com/sous-chefs/mysql/files/5669286/stacktrace.txt)

**Comment by ramereth** [comment]
I've confirm this happening if you remove the apparmor cookbook and references from the test cookbook. It seems to be related to ` node['apparmor']['disable']` being `nil` as noted here:

https://github.com/sous-chefs/mysql/blob/844036bde95721c401ce5309007787babdfc412d/libraries/mysql_service_base.rb#L126

I bet you if you include the apparmor cookbook in your wrapper cookbook, this problem will go away. We should probably fix that line of code to account for the fact if the apparmor cookbook isn't included.

Feel free to make a PR to fix this otherwise we'll get to this as soon as we can.

Thanks!
